sudo: required
language: go
go: 1.13.x
services:
  - docker
before_install:
  - docker pull mysql:5.7
  - docker run -e MYSQL_ROOT_PASSWORD=root -d -p 127.0.0.1:3307:3306 mysql:5.7
  - docker ps -a
script:
  - cp ./config/config.example.yml ./config/config.yml
  - go run concat.go
  - sleep 30
  - echo "create database dol;" | mysql -h 127.0.0.1 -u root -P 3307 --password=root
  - cat public-db.sql | mysql -h 127.0.0.1 -u root -P 3307 --password=root -D dol
  - cd ../.. && ./test_sql_scripts.sh
